//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tempapp.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DEMO_APP_XEMPHIMEntities : DbContext
    {
        public DEMO_APP_XEMPHIMEntities()
            : base("name=DEMO_APP_XEMPHIMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnhDaiDien> AnhDaiDiens { get; set; }
        public virtual DbSet<ChuDe> ChuDes { get; set; }
        public virtual DbSet<Cua_NguoiDung_Quyen> Cua_NguoiDung_Quyen { get; set; }
        public virtual DbSet<Cua_Phim_Luat> Cua_Phim_Luat { get; set; }
        public virtual DbSet<Cua_Phim_Studio> Cua_Phim_Studio { get; set; }
        public virtual DbSet<Cua_Phim_TacGia> Cua_Phim_TacGia { get; set; }
        public virtual DbSet<Cua_Phim_TheLoai> Cua_Phim_TheLoai { get; set; }
        public virtual DbSet<Luat> Luats { get; set; }
        public virtual DbSet<Mua> Muas { get; set; }
        public virtual DbSet<NguoiDung> NguoiDungs { get; set; }
        public virtual DbSet<NguoiDung_BinhLuan_Phim> NguoiDung_BinhLuan_Phim { get; set; }
        public virtual DbSet<NguoiDung_DanhGia_Phim> NguoiDung_DanhGia_Phim { get; set; }
        public virtual DbSet<NguoiDung_Xem_Phim> NguoiDung_Xem_Phim { get; set; }
        public virtual DbSet<Phim> Phims { get; set; }
        public virtual DbSet<Quyen> Quyens { get; set; }
        public virtual DbSet<Studio> Studios { get; set; }
        public virtual DbSet<TacGia> TacGias { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<TheLoai> TheLoais { get; set; }
        public virtual DbSet<ThongTin_NguoiDung> ThongTin_NguoiDung { get; set; }
        public virtual DbSet<TrangThai> TrangThais { get; set; }
        public virtual DbSet<VIDEO> VIDEOs { get; set; }
    }
}
