//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tempapp.Model
{
    using System;
    using System.Collections.Generic;

    public partial class NguoiDung_Xem_Phim
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> NgayXem { get; set; }
        public Nullable<int> IdNguoiDung { get; set; }
        public Nullable<int> IdPhim { get; set; }

        public virtual NguoiDung NguoiDung { get; set; }
        public virtual Phim Phim { get; set; }
    }
}

